app:
  topic:
    name: payment

server:
  port: 9095
spring:
  application:
    name: reversed-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
